\name{gcat.analysis.main}
\alias{gcat.analysis.main}
\title{Top-level data analysis for GCAT}
\description{
User-level function to run a complete analysis with graphic output on data in either 
the single-plate (wide) or multiple-plate (long) format. It calls on the subfunctions
\code{\link{gcat.fit.main}} along with \code{\link{gcat.output.main}}.
}
\usage{
gcat.analysis.main(file.list, single.plate, layout.file = NULL, 
out.dir = getwd(), graphic.dir = paste(out.dir, "/pics", sep = ""),
time.format = "\%Y-\%m-\%d \%H:\%M:\%S", plate.nrow = 8, plate.ncol = 12, 
add.constant = 1, blank.value = NULL, start.index = 2, growth.cutoff = 0.05
points.to.remove = 0, remove.jumps = F, silent = T,
verbose = F, return.fit = F, overview.jpgs = T)
}
\arguments{
  \item{file.name}{
A list of complete path and file names of .csv files containing growth curve data in the single-plate 
(wide) or multiple-plate (long) format. GCAT will analyze them in sequence and append the results 
together in the output. See GCAT documentation for specific description of formats.
}
  \item{single.plate}{
Is the input data in the single-plate (wide) format? If yes, GCAT calls 
%\code{\link{gcat.reorganize.single.plate.data}} to convert it to the multiple-plate (long) format.
\code{gcat.reorganize.single.plate.data} to convert it to the multiple-plate (long) format.
} 
  \item{layout.file}{
If \code{load.type} is "csv", this argument specifies the location of a layout file containing
identifying information. See GCAT documentation for specific description of formats.  
}
  \item{out.dir}{
Name a directory to which GCAT will export text results.
Defaults to working directory.
}
  \item{graphic.dir}{
Name a directory to which GCAT will export graphics results.
Defaults to a "pics" subdirectory of \code{out.dir}.
Note: directories will be created if not existant.
}
  \item{add.constant}{
A value for n in the log(OD + n) transformation.
}
  \item{blank.value}{
Blank OD measurement for uninoculated wells. By default (NULL),
the value of the first OD measurement in each well is used.
}
  \item{start.index}{
Which timepoint should be used as the first one after inoculation?
}
  \item{points.to.remove}{
A vector of integers specifying which timepoints should be removed
across all wells. By default (0), none are marked for removal.
}
  \item{remove.jumps}{
Should jumps in OD detected by the subfunction \code{check.slopes} be removed?
}
\item{growth.cutoff}{
A threshold used by \code{check.growth} to decide whether a well displays growth. 
}
  \item{silent}{
Should all messages returned to the R console
(by this function and its sub-functions) be suppressed?
}
  \item{verbose}{
Should sub-functions return lengthy messages to the console?
}
  \item{return.fit}{
See \code{value} below.
}
  \item{overview.jpgs}{
Should .jpg files of the plate overviews be generated and added to \code{graphic.dir}?
}
}
\value{
If \code{return.fit = T}, an array of multiple \code{well} objects containing
the original data sorted into wells and model fits.

If \code{return.fit = F}, a vector of full paths to all output generated by
this function.
}
\author{
J. Shao
}
\seealso{
  \code{gcat.fit.main}, \code{gcat.output.main}
}